### ISSUE TITLE
 json_serializable build error

### ISSUE THREAD

**Issue by keremcankabadayi** [diezep/heroku-buildpack-flutter#11]
Hi there, I'm trying this build-pack but I have a build error about `json_serializable `library. It needs to run `flutter pub run build_runner build`. How can i achieve that? Maybe my app configuration is wrong, i'm also new at flutter.

```
part 'subscription.g.dart';

     ^

lib/models/subscription.dart:3:6:

Error: Can't use 'lib/models/subscription.g.dart' as a part, because it has no 'part of' declaration.

part 'subscription.g.dart';

     ^

lib/models/subscription.dart:13:7:

Error: Method not found: '_$SubscriptionFromJson'.

      _$SubscriptionFromJson(json);

      ^^^^^^^^^^^^^^^^^^^^^^

lib/models/subscription.dart:15:36:

Error: The method '_$SubscriptionToJson' isn't defined for the class 'Subscription'.

 - 'Subscription' is from 'package:trade_bot/models/subscription.dart' ('lib/models/subscription.dart').

  Map<String, dynamic> toJson() => _$SubscriptionToJson(this);

                                   ^^^^^^^^^^^^^^^^^^^^

Error: Compilation failed.
```

**Comment by keremcankabadayi** [comment]
Okey, I think it works. *.g.dart files shouldnt be added .gitignore. If you dont have any comment or suggestion, you can close it issue.

**Comment by diezep** [comment]
You can customize the command when the project will be build, and write something like `flutter pub run build_runner build && flutter build web --release`
