### ISSUE TITLE
[remote rejected] master -> main (pre-receive hook declined)

### ISSUE THREAD

**Issue by ag-0214** [diezep/heroku-buildpack-flutter#7]
Hi,
I am working on a flutter project that i want to deploy on heroku using your buildpack. I followed other steps, after running heroku buildpacks:set diezep/flutter -a <Heroku App name>and get the meesage
Buildpack set. Next release on herokuappname will use diezep/flutter.
Run git push heroku main to create a new release using this buildpack.
I run this command git push heroku master:main 
Results
Enumerating objects: 97, done.
Counting objects: 100% (97/97), done.
Delta compression using up to 8 threads
Compressing objects: 100% (79/79), done.
Writing objects: 100% (97/97), 56.05 KiB | 2.24 MiB/s, done.
Total 97 (delta 7), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> https://buildpack-registry.s3.amazonaws.com/buildpacks/diezep/flutter.tgz app detected
remote: -----> Installing SDK from Github repository.
remote: -----> Running flutter upgrade command
remote: Downloading Dart SDK from Flutter engine 609036f2bf7cae17a0b88c21fb3bdaff7159b713...
remote:          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                         Dload  Upload   Total   Spent    Left  Speed
remote: 100  190M  100  190M    0     0  92.6M      0  0:00:02  0:00:02 --:--:-- 92.6M
remote: Building flutter tool...
remote:
remote:          ╔════════════════════════════════════════════════════════════════════════════╗
remote:          ║                 Welcome to Flutter! - https://flutter.dev                  ║
remote:          ║                                                                            ║
remote:          ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
remote:          ║ statistics and basic crash reports. This data is used to help improve      ║
remote:          ║ Flutter tools over time.                                                   ║
remote:          ║                                                                            ║
remote:          ║ Flutter tool analytics are not sent on the very first run. To disable      ║
remote:          ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
remote:          ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
remote:          ║ event will be sent, and then no further information will be sent by the    ║
remote:          ║ Flutter tool.                                                              ║
remote:          ║                                                                            ║
remote:          ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
remote:          ║ Note: The Google Privacy Policy describes how data is handled in this      ║
remote:          ║ service.                                                                   ║
remote:          ║                                                                            ║
remote:          ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
remote:          ║ crash reports to Google.                                                   ║
remote:          ║                                                                            ║
remote:          ║ Read about data we send with crash reports:                                ║
remote:          ║ https://flutter.dev/docs/reference/crash-reporting                         ║
remote:          ║                                                                            ║
remote:          ║ See Google's privacy policy:                                               ║
remote:          ║ https://policies.google.com/privacy                                        ║
remote:          ╚════════════════════════════════════════════════════════════════════════════╝
remote:
remote:        Downloading Material fonts...                                      502ms
remote:        Downloading Gradle Wrapper...                                       12ms
remote:        Downloading package sky_engine...                                  139ms
remote:        Downloading flutter_patched_sdk tools...                         1,076ms
remote:        Downloading flutter_patched_sdk_product tools...                   914ms
remote:        Downloading linux-x64 tools...                                   2,081ms
remote:        Downloading linux-x64/font-subset tools...                         416ms
remote:        Switching to flutter channel 'beta'...
remote: git: Switched to a new branch 'beta'
remote:        git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
remote:        Successfully switched to flutter channel 'beta'.
remote:        To ensure that you're on the latest build from this channel, run 'flutter upgrade'
remote: Downloading Dart SDK from Flutter engine 7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc...
remote:          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                         Dload  Upload   Total   Spent    Left  Speed
remote: 100  173M  100  173M    0     0  98.5M      0  0:00:01  0:00:01 --:--:-- 98.4M
remote: Building flutter tool...
remote:
remote:          ╔════════════════════════════════════════════════════════════════════════════╗
remote:          ║                 Welcome to Flutter! - https://flutter.dev                  ║
remote:          ║                                                                            ║
remote:          ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
remote:          ║ statistics and basic crash reports. This data is used to help improve      ║
remote:          ║ Flutter tools over time.                                                   ║
remote:          ║                                                                            ║
remote:          ║ Flutter tool analytics are not sent on the very first run. To disable      ║
remote:          ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
remote:          ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
remote:          ║ event will be sent, and then no further information will be sent by the    ║
remote:          ║ Flutter tool.                                                              ║
remote:          ║                                                                            ║
remote:          ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
remote:          ║ Note: The Google Privacy Policy describes how data is handled in this      ║
remote:          ║ service.                                                                   ║
remote:          ║                                                                            ║
remote:          ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
remote:          ║ crash reports to Google.                                                   ║
remote:          ║                                                                            ║
remote:          ║ Read about data we send with crash reports:                                ║
remote:          ║ https://flutter.dev/docs/reference/crash-reporting                         ║
remote:          ║                                                                            ║
remote:          ║ See Google's privacy policy:                                               ║
remote:          ║ https://policies.google.com/privacy                                        ║
remote:          ╚════════════════════════════════════════════════════════════════════════════╝
remote:
remote:        Flutter is already up to date on channel beta
remote:        Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
remote:        Framework • revision 5d36f2e7f5 (3 days ago) • 2021-01-14 15:57:49 -0800
remote:        Engine • revision 7a8f8ca02c
remote:        Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
remote: -----> Enabling Web support
remote:        Setting "enable-web" value to "true".
remote:
remote:        You may need to restart any open editors for them to read new settings.
remote: -----> Running flutter clean command.
remote:        Downloading package sky_engine...                                  501ms
remote:        Downloading flutter_patched_sdk tools...                         1,077ms
remote:        Downloading flutter_patched_sdk_product tools...                   932ms
remote:        Downloading linux-x64 tools...                                   2,045ms
remote:        Downloading linux-x64/font-subset tools...                         293ms
remote: -----> Getting packages from Flutter project
remote:        Running "flutter pub get" in build_b95615a5...                   2,020ms
remote: -----> Compiling the project.
remote:        Downloading Web SDK...                                              3.3s
remote: Missing index.html.
remote: -----> Saving Flutter SDK in Cache
remote: mv: cannot stat 'TO_DELETE/build/web/*': No such file or directory
remote:  !     Push rejected, failed to compile https://buildpack-registry.s3.amazonaws.com/buildpacks/diezep/flutter.tgz app.
remote:
remote:  !     Push failed
remote:  !
remote:  ! ## Warning - The same version of this code has already been built: 75d32182cfb0a7726f81e693171f09d0190a4679
remote:  !
remote:  ! We have detected that you have triggered a build from source code with version 75d32182cfb0a7726f81e693171f09d0190a4679
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
remote:  !
remote:  ! If you are developing on a branch and deploying via git you must run:
remote:  !
remote:  !     git push heroku <branchname>:main
remote:  !
remote:  ! This article goes into details on the behavior:
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to herokuappname.
remote:
To https://git.heroku.com/houseofdani.git
 ! [remote rejected] master -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/herokuappnamegit'

May you assist

**Comment by diezep** [comment]
You have to enable Flutter Web in your project and then run “flutter create .”. The following message says that you don’t have an index.html and it’s necessary to compile.

remote: Downloading Web SDK... 3.3s
remote: Missing index.html.

**Comment by ag-0214** [comment]
Thanks
